### ISSUE TITLE
comma-style throw error in v-slot

### ISSUE THREAD

**Issue by zWingz** [vuejs/eslint-plugin-vue#1168]
```html
 <a
    v-slot="scope"
  >
    <slot />
  </a>
```

throw error

```
TypeError: coreHandlers.FunctionExpression is not a function
Occurred while linting /Users/xxxx/project/src/components/xxx.vue:25
    at EventEmitter.VSlotScopeExpression (/Users/xxxx/project/node_modules/eslint-plugin-vue/lib/rules/comma-style.js:17:24)
    at EventEmitter.emit (events.js:198:13)
    at NodeEventGenerator.applySelector (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:3309:26)
    at NodeEventGenerator.applySelectors (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:3323:22)
    at NodeEventGenerator.enterNode (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:3331:14)
    at traverse (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:115:13)
    at traverse (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:127:13)
    at traverse (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:127:13)
    at traverse (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:122:21)
    at traverse (/Users/xxxx/project/node_modules/eslint-plugin-vue/node_modules/vue-eslint-parser/index.js:127:13)

```

* **ESLint version:**	
7.1.0
* **eslint-plugin-vue version:**	
7.0.0-alpha.4
* **Node version:**	
10.16.3

**Comment by ota-meshi** [comment]
Thank you for this issue.

I will check this bug from now.
