### ISSUE TITLE
crash when using the vue/no-empty-component-block rule on a .js file

### ISSUE THREAD

**Issue by danyadev** [vuejs/eslint-plugin-vue#1230]
**Tell us about your environment**	
* **ESLint version:** 7.3.1
* **eslint-plugin-vue version:** 7.0.0-alpha.8
* **Node version:**	v12.18.2

**Please show your full configuration:**

```js
{
  root: true,

  parserOptions: {
    sourceType: 'module'
  },

  env: {
    browser: true,
    node: true,
    es2020: true
  },

  extends: ['plugin:vue/vue3-recommended'],

  rules: [
    // *other rules*
    'vue/no-empty-component-block': 'error'
  ]
}
```

**What did you do?**	
I launched the linter for the .js file

**What did you expect to happen?**
plugin works

**What actually happened?**
```
Oops! Something went wrong! :(

ESLint: 7.3.1

TypeError: Error while loading rule 'vue/no-empty-component-block': Cannot read property 'children' of null
Occurred while linting C:\Users\danyadev\Desktop\vk-desktop\src\components\auth\index.js
    at Object.create (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint-plugin-vue\lib\rules\no-empty-component-block.js:75:7)
    at createRuleListeners (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:758:21)
    at C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:928:31
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:873:34)
    at Linter._verifyWithoutProcessors (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1170:31)
    at Linter._verifyWithConfigArray (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1268:21)
    at Linter.verify (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1223:25)
    at Linter.verifyAndFix (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1413:29)
    at verifyText (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\cli-engine\cli-engine.js:224:48)
    at CLIEngine.executeOnFiles (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\cli-engine\cli-engine.js:788:28)
    at ESLint.lintFiles (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\eslint\eslint.js:515:23)
    at Object.execute (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\cli.js:294:36)
    at main (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\bin\eslint.js:142:52)
    at Object.<anonymous> (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\bin\eslint.js:146:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
```

**Comment by danyadev** [comment]
Oh, crash happens not only with this rule, but also with `vue/padding-line-between-blocks`:

```
TypeError: Cannot read property 'children' of null
Occurred while linting C:\Users\danyadev\Desktop\vk-desktop\src\components\auth\index.js:1
    at getTopLevelHTMLElements (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint-plugin-vue\lib\rules\padding-line-between-blocks.js:154:31)
    at Program (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint-plugin-vue\lib\rules\padding-line-between-blocks.js:201:32)
    at C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:635:23)
    at C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:949:32
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:944:15)
    at Linter._verifyWithoutProcessors (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1170:31)
    at Linter._verifyWithConfigArray (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1268:21)
    at Linter.verify (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1223:25)
    at Linter.verifyAndFix (C:\Users\danyadev\Desktop\vk-desktop\node_modules\eslint\lib\linter\linter.js:1413:29)
```

**Comment by danyadev** [comment]
Going back to ESLint 7.2.0 (where everything worked together with the previous version of this plugin) did not help.

**Comment by danyadev** [comment]
Also, regardless of the eslint version, this error is returned:

```
Error while parsing C:\Users\danyadev\Desktop\vk-desktop\node_modules\vue-router\dist\vue-router.esm.js
Line 270, column 23: Unexpected token {
`parseForESLint` from parser `C:\Users\danyadev\Desktop\vk-desktop\node_modules\vue-eslint-parser\index.js` is invalid and will just be ignored
```

Although similar errors come from eslint-plugin-import:

```
C:\Users\danyadev\Desktop\vk-desktop\src\js\router.js
  1:51  error  Parse errors in imported module 'vue-router': Unexpected token { (270:23)  import/namespace
  1:51  error  Parse errors in imported module 'vue-router': Unexpected token { (270:23)  import/named
```

**Comment by danyadev** [comment]
This error began to appear since version vue-router 4.0.0-alpha.13 and higher...
(error on line 273)
![image](https://user-images.githubusercontent.com/35631027/86480834-76bb1d00-bd57-11ea-8d18-5607059d73e8.png)

**Comment by ota-meshi** [comment]
Thank you for this issue. The first problem is probably a bug.

The cause of the parsing error is your setting is missing.
You need to add `"ecmaVersion": 2019`.

```json
{
    "parserOptions": {
        "ecmaVersion": 2019
    },
}
```

https://eslint.org/docs/user-guide/configuring#specifying-parser-options

**Comment by danyadev** [comment]
Thanks, it helped!
