### ISSUE TITLE
got "Error: Failed to load config "plugin:vue/recommended" to extend from." on the latest release

### ISSUE THREAD

**Issue by handhikadj** [vuejs/eslint-plugin-vue#1354]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:*7.13.0* 
- **eslint-plugin-vue version:*7.1.0* 
- **Node version:*14.14.0 and node:lts-alpine on docker*  
- **Operating System:*Mac OS Catalina and docker alpine* 

**Please show your full configuration:**

```json5
{
   "root":true,
   "env":{
      "browser":true,
      "node":true
   },
   "globals":{
      "$nuxt":true
   },
   "parser": "vue-eslint-parser",
   "parserOptions":{
      "parser":"babel-eslint"
   },
   "extends":[
      "plugin:vue/recommended",
      "eslint:recommended",
      "prettier/vue",
      "plugin:prettier/recommended"
   ],
   "rules":{
      "prettier/prettier":[
         "error",
         {
            "trailingComma":"es5",
            "singleQuote":true,
            "printWidth":120,
            "tabWidth":4
         }
      ],
      "vue/script-indent":[
         "error",
         4,
         {
            "baseIndent":1
         }
      ],
      "vue/component-name-in-template-casing":[
         "error",
         "PascalCase"
      ],
      "no-console":0,
      "no-debugger":0
   }
}
```

**What did you do?**	

the error shows up during `npm run serve`

**What did you expect to happen?**
the error message should go away

**What actually happened?**

<details><summary>Click to expand log</summary>

```
ERROR  Failed to compile with 1 errors                                                                                                                                 9:15:24 PM

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load config "plugin:vue/recommended" to extend from.
Referenced from: myapp/.eslintrc.json
    at configMissingError (myapp/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
    at ConfigArrayFactory._loadExtendedPluginConfig (myapp/node_modules/@eslint/eslintrc/lib/config-array-factory.js:844:31)
    at ConfigArrayFactory._loadExtends (myapp/node_modules/@eslint/eslintrc/lib/config-array-factory.js:778:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (myapp/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (myapp/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (myapp/node_modules/@eslint/eslintrc/lib/config-array-factory.js:510:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (myapp/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:378:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (myapp/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:397:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (myapp/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:18)
    at CLIEngine.isPathIgnored (myapp/node_modules/eslint/lib/cli-engine/cli-engine.js:972:18)
    at CLIEngine.executeOnText (myapp/node_modules/eslint/lib/cli-engine/cli-engine.js:883:38)
    at lint (myapp/node_modules/eslint-loader/index.js:278:17)
    at transform (myapp/node_modules/eslint-loader/index.js:252:18)
    at myapp/node_modules/loader-fs-cache/index.js:127:18

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

**Repository to reproduce this issue**

**Comment by bayssmekanique** [comment]
Same on Windows with `ESLint: 7.13.0`, `Node: 14.2.0`.

**Comment by handhikadj** [comment]
fixed. unmet peer dependencies issue

**Comment by georgezouq** [comment]
@handhikadj How to fix this?

**Comment by handhikadj** [comment]
This issue has been so long. I'd try my best to explain this to you. "Unmet peer dependencies" means certain dependencies don't match with another dependencies on your app
