### ISSUE TITLE
Import in body of module; reorder to top. eslint(import/first)

### ISSUE THREAD

**Issue by lipengzhou** [vuejs/eslint-plugin-vue#1577]
**Checklist**

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: 7.31.0** 
- **eslint-plugin-vue version: 7.14.0** 
- **Node version: 14.15.1** 
- **Operating System: Windows 10** 

**Please show your full configuration:**

```json5
module.exports = {
  globals: {
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    withDefaults: 'readonly'
  },
  env: {
    browser: true,
    es2021: true
  },
  extends: ['plugin:vue/vue3-strongly-recommended', 'standard'],
  parserOptions: {
    ecmaVersion: 12,
    parser: '@typescript-eslint/parser',
    sourceType: 'module'
  },
  plugins: ['vue', '@typescript-eslint'],
  rules: {}
}

```

**What did you do?**	

```vue
<script lang="ts">
export default {
  name: 'HomeIndex'
}
</script>

<script lang="ts" setup>
import foo from './foo.vue'

</script>
```

**What did you expect to happen?**

If use alongside normal <script> ，the script setup below will cause this error：error  Import in body of module; reorder to top  import/first。

**What actually happened?**

```
error  Import in body of module; reorder to top  import/first
```

**Repository to reproduce this issue**

**Comment by ota-meshi** [comment]
As far as I know, it's technically impossible to be compatible with that rule.  Please let me know if anyone knows a good way.

**Comment by Mootook** [comment]
What about just disabling the rule?

```js
// .eslintrc.js
{
// options
  rules: {
    'import/first': 'off'
  }
}
```

**Comment by kalvenschraut** [comment]
Would there be a way to just have it disabled for files that use script setup? Ideally this is enforced where applicable and if script setup can not be in compliance with it I would rather not turn it off completely for my whole entire project.

Is it not possible to enforce the rule in the sense that the imports are always at the top of each individual script tag?

I.E. below is fine

``` html
<script>
import foo from 'bar'

// some code
</script>
<script setup>
import otherModule from 'baz'

// some code
<script>
```

while the below would report the error

``` html
<script>
import foo from 'bar'

// some code
</script>
<script setup>
// some code

 // error here since import is not at the top of the script tag
import otherModule from 'baz'
</script>
```

**Comment by FloEdelmann** [comment]
I think there is nothing we can do about this in `eslint-plugin-vue`, as this error is caused by `eslint-plugin-import` and Vue core.

@ota-meshi @mysticatea Maybe [`vue-eslint-parser`](https://github.com/vuejs/vue-eslint-parser) could do something to fix this?

**Comment by sadeghbarati** [comment]
same here

[#81](https://github.com/antfu/eslint-config/issues/81)

**Comment by ahnpnl** [comment]
+1 for this. I ran into the same issue

**Comment by morgan-atproperties** [comment]
As noted in #1700 if you run eslint with the `--fix` flag, the linter will actually rearrange your `<script>` and `<script setup>` blocks, potentially changing the meaning of the Vue code.

```
<script lang="ts">
export default {
  name: 'HomeIndex'
}
</script>

<script lang="ts" setup>
import foo from './foo.vue'

</script>
```
changes to
```
<script lang="ts">
</script>

<script lang="ts" setup>
import foo from './foo.vue'
export default {
  name: 'HomeIndex'
}

</script>
```
The automated linter will move the export to the wrong block.

Any user of eslint-plugin-vue should probably set `'import/first': 'off'` until this is fixed.  You don't want your linter silently changing the meaning of your Vue code.

**Comment by morgan-atproperties** [comment]
Here is a more complete example.

```
<!--
 Modified version of script setup example
 documented here: https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script
-->

<script>
// normal <script>, executed in module scope (only once)
const runSideEffectOnce = () => {}
runSideEffectOnce()

// declare additional options
export default {
  inheritAttrs: false,
  customOptions: {}
}
</script>

<script setup>
// executed in setup() scope (for each instance)
import HelloWorld from './HelloWorld.vue'
HelloWorld.hello()
</script>
```

becomes

```
<script>
// normal <script>, executed in module scope (only once)
</script>

<script setup>
// executed in setup() scope (for each instance)
import HelloWorld from './HelloWorld.vue'
const runSideEffectOnce = () => {}
runSideEffectOnce()

// declare additional options
export default {
  inheritAttrs: false,
  customOptions: {}
}
HelloWorld.hello()
</script>

```

**Comment by basil-gor** [comment]
Hello everyone!
I have the same troubles.
Maybe there are some updates on how to solve this problem without disabling the eslint rule?

**Comment by nestle49** [comment]
Any updates?

**Comment by FloEdelmann** [comment]
No, please see the comment thread above. If a fix or workaround can be found (and it's not clear if that's possible at all), it will be commented here. Please only comment new information in this issue and stop asking for updates.

**Comment by FloEdelmann** [comment]
In Vue 3.3, you can now use `defineOptions` in `<script setup>` and avoid this issue altogether, see https://blog.vuejs.org/posts/vue-3-3#defineoptions and https://vuejs.org/api/sfc-script-setup.html#defineoptions.

```vue
<script lang="ts" setup>
import foo from './foo.vue'

defineOptions({
  name: 'HomeIndex'
})
</script>
```

**Comment by orimay** [comment]
> In Vue 3.3, you can now use `defineOptions` in `<script setup>` and avoid this issue altogether, see https://blog.vuejs.org/posts/vue-3-3#defineoptions and https://vuejs.org/api/sfc-script-setup.html#defineoptions.
> 
> ```
> <script lang="ts" setup>
> import foo from './foo.vue'
> 
> defineOptions({
>   name: 'HomeIndex'
> })
> </script>
> ```

But we may want to export something, for instance, an injection key from the component

**Comment by FloEdelmann** [comment]
But `export` statements should be unaffected by this issue, aren't they? You can put them anywhere in the `<script setup>` block.

**Comment by orimay** [comment]
No, you can only export from script block, as script setup goes into setup function:
https://play.vuejs.org/#eNp9UkFOwzAQ/IrxJSCVRAi4lLQSoErAARAgcfElSrapi2NbthMiRf47a4eWIrW9eWdm17MeD/RW67RrgU5pbkvDtSMWXKvnTPJGK+PIQAwsiSdLoxqSoDTZoYotkWb3qomjkGeyVNI60tiazEL/afIAQijyqYyoTpIzJvNsvA4vwsJBo0XhACtC8tXFfBhis/d5hlVEudStI915oyoQM0aRZ5RkkUT5aMb7MHpnHJ1QZ9HNktfp2iqJiw6hg9ES/XIB5kU7jm4ZnZLIBK5As99PEXOmhckGL1dQfu3B17YPGKOvBiyYDhjdcq4wNbiRXrw/Q4/nLYnLtALVR8g3sEq0weMou2tlhbZ3dNHtY8yEy/rDLnoH0m6WCkaD0kc9oxhRiOrQ6n92L9Or2Mekx1fcxLvnp0Afv8OYeYGJX98cD7jiXTzg0QrlfkPMsxH/n5//AeBC3+s=
```
Error: [@vue/compiler-sfc] <script setup> cannot contain ES module exports. If you are using a previous version of <script setup>, please consult the updated RFC at https://github.com/vuejs/rfcs/pull/227.

src/Comp.vue
1  |  <script setup>
   |                 ^
2  |  export const a = 5;
   |  ^^^^^^^^^^^^^^^^^^^
3  |  </script>
    at $Re.error (https://play.vuejs.org/assets/index-nQHpgkA0.js:187:397)
    at Module.WMe [as compileScript] (https://play.vuejs.org/assets/index-nQHpgkA0.js:223:1732)
    at ine (https://play.vuejs.org/assets/index-nQHpgkA0.js:821:215)
    at nT (https://play.vuejs.org/assets/index-nQHpgkA0.js:814:5142)
```

**Comment by JessicaSachs** [comment]
Here's the overrides workaround to disable the rule (Eslint flat config)

```ts
export default [{
  plugins: { /** Plugins and such */ },
  rules: { /** Rules to setup eslint */ },
  overrides: [
    {
      files: ['*.vue'],
      rules: {
        'import/first': 'off',
      },
    },
  ]
}]
```
