### ISSUE TITLE
vue/html-indent errors while using <textarea>

### ISSUE THREAD

**Issue by cheeze2000** [vuejs/eslint-plugin-vue#1752]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.6.0
- **eslint-plugin-vue version:** 8.2.0
- **Node version:** 16.13.1
- **Operating System:** Ubuntu 20.04.3 

**Please show your full configuration:**

```js
module.exports = {
	"env": {
		"commonjs": true,
	},
	"extends": [
		"eslint:recommended",
		"plugin:vue/vue3-strongly-recommended"
	],
	"parserOptions": {
		"ecmaVersion": 13,
		"sourceType": "module"
	},
	"plugins": [
		"vue"
	],
	"rules": {
		"vue/html-indent": ["error", "tab"]
	}
};
```

**What did you do?**	

```vue
<template>
	<textarea class="red">
		abc
</template>
```

**What did you expect to happen?**
Linting errors about missing a closing textarea tag

**What actually happened?**

```
Oops! Something went wrong! :(

ESLint: 8.6.0

TypeError: Cannot read properties of null (reading 'range')
Occurred while linting /home/cheeze/repos/test-app/App.vue:1
Rule: "vue/html-indent"
    at TokenStore.getTokensBetween (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:4240:107)
    at setPreformattedTokens (/home/cheeze/repos/test-app/node_modules/eslint-plugin-vue/lib/utils/indent-common.js:314:36)
    at EventEmitter.VElement (/home/cheeze/repos/test-app/node_modules/eslint-plugin-vue/lib/utils/indent-common.js:971:9)
    at EventEmitter.emit (node:events:402:35)
    at NodeEventGenerator.applySelector (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:3826:26)
    at NodeEventGenerator.applySelectors (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:3840:22)
    at NodeEventGenerator.enterNode (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:3848:14)
    at traverse (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:117:13)
    at traverse (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:124:21)
    at traverseNodes (/home/cheeze/repos/test-app/node_modules/vue-eslint-parser/index.js:135:5)
```

**Repository to reproduce this issue**

[https://github.com/cheeze2000/eslint-vue-error](https://github.com/cheeze2000/eslint-vue-error)
To reproduce the error, `npm install` and `npm run lint`.

**Comment by cheeze2000** [comment]
A more minimal `App.vue`:
```vue
<template>
	<textarea>
</template>
```

However, changing the `<textarea>` to other tags like `<p>` does not throw any error.

**Comment by ota-meshi** [comment]
Thank you for posting this issue and providing repository to reproduce the issue.
