### ISSUE TITLE
Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by HelloDeadline** [vuejs/eslint-plugin-vue#183]
Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object

**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **eslint-plugin-vue Version:**  3.13.0
* **Node Version:** 8.4.0

I'm using ESLint in Visual Studio Code. But the same issue appears in console.

**Please show your full configuration:**

```
{
  "extends": ["airbnb-base", "plugin:vue/recommended"],
  "plugins": ["vue", "html", "class-property"],
  "parser": "vue-eslint-parser",
  "parserOptions": {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "rules": {
    "import/no-unresolved": 0,
    "import/no-unassigned-import": 0,
    "import/no-extraneous-dependencies": 0,
    "import/extensions": 0,
    "class-property/rule-name": 2
  }
}

```

**What did you do? Please include the actual source code causing the issue.**

I don't have any v-if or v-for in the project. Eslint simply never starts to lint in this conditions.

**What did you expect to happen?**

It starts linting

**What actually happened? Please include the actual, raw output from ESLint.**
```cli
> eslint client/**/*.{vue,js}

Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
TypeError: Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys.filter.forEach.key (/home/s/Git/decompose/node_modules/eslint/lib/eslint.js:872:28)
    at Array.forEach (<anonymous>)
    at EventEmitter.module.exports.api.verify (/home/s/Git/decompose/node_modules/eslint/lib/eslint.js:841:93)
    at localVerify (/home/s/Git/decompose/node_modules/eslint-plugin-html/src/index.js:107:14)
    at EventEmitter.eslint.verify (/home/s/Git/decompose/node_modules/eslint-plugin-html/src/index.js:147:18)
    at processText (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:264:31)
    at processFile (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:672:25)
    at fileList.forEach.fileInfo (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:710:13)

```

**Comment by HelloDeadline** [comment]
After updating Eslint to 4.6.1

```cli
> eslint client/**/*.{vue,js}

AST is missing the tokens array.
Error: AST is missing the tokens array.
    at validate (/home/s/Git/decompose/node_modules/eslint/lib/util/source-code.js:30:15)
    at SourceCode (/home/s/Git/decompose/node_modules/eslint/lib/util/source-code.js:117:9)
    at Linter.verify (/home/s/Git/decompose/node_modules/eslint/lib/linter.js:878:31)
    at localVerify (/home/s/Git/decompose/node_modules/eslint-plugin-html/src/index.js:107:14)
    at Linter.eslint.verify (/home/s/Git/decompose/node_modules/eslint-plugin-html/src/index.js:147:18)
    at processText (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:203:31)
    at processFile (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:245:18)
    at executeOnFile (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:585:25)
    at fileList.forEach.fileInfo (/home/s/Git/decompose/node_modules/eslint/lib/cli-engine.js:622:13)
    at Array.forEach (<anonymous>)

```

**Comment by HelloDeadline** [comment]
### Solved. I needed to remove parser at all. 
```
{
  "extends": ["airbnb-base", "plugin:vue/recommended"],
  "plugins": ["vue", "html", "class-property"],
  "parserOptions": {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "rules": {
    "import/no-unresolved": 0,
    "import/no-unassigned-import": 0,
    "import/no-extraneous-dependencies": 0,
    "import/extensions": 0,
    "class-property/rule-name": 2
  }
}
```

**Comment by GeoffZhu** [comment]
Hi, @HelloDeadline  
I checked the configuration of ESlint, There is no ```parser option```  in parserOptions, where you find it?

**Comment by GeoffZhu** [comment]
Find It , It's a option of [vue-eslint-parser](https://github.com/mysticatea/vue-eslint-parser)

**Comment by 3Dcube** [comment]
I have the same issue

- **ESLint Version:** 4.9.0
- **Node Version:** v8.7.0
- **eslint-plugin-vue:** 3.13.1

```js
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:vue/recommended'
  ],
  plugins: [
    'vue',
    'html'
  ],
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

```
output:
```
PS D:\dev\my-project> npm run lint

> my-project@1.0.0 lint D:\dev\my-project
> eslint --ext .js,.vue src test/unit/specs

Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
TypeError: Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys.forEach.ruleId (D:\dev\my-project\node_modules\eslint\lib\linter.js:927:24)
    at Array.forEach (<anonymous>)
    at Linter._verifyWithoutProcessors (D:\dev\my-project\node_modules\eslint\lib\linter.js:864:35)
    at preprocess.map.textBlock (D:\dev\my-project\node_modules\eslint\lib\linter.js:993:35)
    at Array.map (<anonymous>)
    at Linter.verify (D:\dev\my-project\node_modules\eslint\lib\linter.js:992:42)
    at localVerify (D:\dev\my-project\node_modules\eslint-plugin-html\src\index.js:107:14)
    at currentInfos.code.forEach (D:\dev\my-project\node_modules\eslint-plugin-html\src\index.js:135:13)
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@1.0.0 lint: `eslint --ext .js,.vue src test/unit/specs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-10-15T05_29_34_867Z-debug.log
```

**Comment by mysticatea** [comment]
@3Dcube See [this section](https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error).

**Comment by 3Dcube** [comment]
thanks
