### ISSUE TITLE
How does the flat configuration of eslint-plugin-vue only apply to vue files

### ISSUE THREAD

**Issue by lvzhenbo** [vuejs/eslint-plugin-vue#2603]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 9.14.0
- **eslint-plugin-vue version:** 9.30.0
- **Vue version:** 3.5.12
- **Node version:** 22
- **Operating System:** win11 2402

**Please show your full configuration:**

```json5
import { defineFlatConfig } from 'eslint-define-config';
import js from '@eslint/js';
import pluginVue from 'eslint-plugin-vue';
import vueTsEslintConfig from '@vue/eslint-config-typescript';
import prettierConfig from '@vue/eslint-config-prettier';
import parserVue from 'vue-eslint-parser';
import AutoImport from './.eslintrc-auto-import.json' with { type: 'json' };
import markdown from '@eslint/markdown';

export default defineFlatConfig([
  ...pluginVue.configs['flat/recommended'],
  js.configs.recommended,
  ...vueTsEslintConfig({
    supportedScriptLangs: {
      ts: true,
      tsx: true,
    },
  }),
  {
    name: 'app/vue-files',
    files: ['**/*.vue'],
    languageOptions: {
      parser: parserVue,
      parserOptions: {
        ecmaVersion: 'latest',
      },
    },
  },
  {
    name: 'app/files-to-lint',
    files: ['**/*.{ts,mts,tsx,vue}'],
    languageOptions: {
      globals: {
        ...AutoImport.globals,
      },
    },
    rules: {
      // 允许被禁止的类型 https://typescript-eslint.io/rules/ban-types/
      '@typescript-eslint/ban-types': 'off',
      // 允许any类型 https://typescript-eslint.io/rules/no-explicit-any/
      '@typescript-eslint/no-explicit-any': 'off',
      // 允许任何TS指令注释 https://typescript-eslint.io/rules/ban-ts-comment
      '@typescript-eslint/ban-ts-comment': 'off',
      // 允许空函数 https://typescript-eslint.io/rules/no-empty-function/
      '@typescript-eslint/no-empty-function': 'off',
      // 关闭强制多词组件名 https://eslint.vuejs.org/rules/multi-word-component-names.html
      'vue/multi-word-component-names': 'off',
      // 强制执行自我关闭风格 https://eslint.vuejs.org/rules/html-self-closing.html
      'vue/html-self-closing': [
        'error',
        {
          html: {
            void: 'always',
            normal: 'never',
            component: 'always',
          },
          svg: 'always',
          math: 'always',
        },
      ],
    },
  },
  {
    name: 'app/files-to-ignore',
    ignores: ['**/dist/**', '**/dist-ssr/**', '**/coverage/**'],
  },
  prettierConfig,
  {
    name: 'app/markdown-files',
    files: ['**/*.md'],
    plugins: {
      markdown,
    },
    language: 'markdown/commonmark',
    rules: {
      'markdown/no-html': 'error',
    },
  },
]);

```

**What did you do?**	

I am planning to use the @ eslint/markdown package to solve the formatting problem of MD files

**What did you expect to happen?**
ESLint should be running normally

**What actually happened?**

```
[Error - 13:31:37] An unexpected error occurred:
[Error - 13:31:37] TypeError: Error while loading rule 'vue/multi-word-component-names': Cannot read properties of undefined (reading 'getDocumentFragment')
Occurred while linting C:\Users\htk\Desktop\localStorage-manager\README.md
    at getScriptSetupElement (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint-plugin-vue@9.30.0_eslint@9.14.0_jiti@1.21.6_\node_modules\eslint-plugin-vue\lib\utils\index.js:2702:31)
    at Object.isScriptSetup (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint-plugin-vue@9.30.0_eslint@9.14.0_jiti@1.21.6_\node_modules\eslint-plugin-vue\lib\utils\index.js:2692:18)
    at Object.create (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint-plugin-vue@9.30.0_eslint@9.14.0_jiti@1.21.6_\node_modules\eslint-plugin-vue\lib\rules\multi-word-component-names.js:55:24)
    at createRuleListeners (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint@9.14.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:943:21)
    at C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint@9.14.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:1068:84
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint@9.14.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:999:34)
    at #flatVerifyWithoutProcessors (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint@9.14.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint@9.14.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:1992:49)
    at Linter._verifyWithFlatConfigArray (C:\Users\htk\Desktop\localStorage-manager\node_modules\.pnpm\eslint@9.14.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:2081:21)
```

**Repository to reproduce this issue**

https://github.com/lvzhenbo/localStorage-manager

**Comment by waynzh** [comment]
It's not just `pluginVue`, you also have other global configurations(`vueTsEslintConfig` etc.) that would affect all files.
For example, the `README.md` file would be affected by these rules:
<img width="780" alt="image" src="https://github.com/user-attachments/assets/6a5475d3-dd61-4076-9bf0-66b48d4a3aee">

**Comment by lvzhenbo** [comment]
@waynzh yes so I'm trying to solve them one by one, the error I've seen so far is from `eslint-plugin-vue`, how is this solved, I didn't see a note about it

**Comment by lvzhenbo** [comment]
@waynzh I configured it according to the [official website](https://eslint.vuejs.org/user-guide/#configuration-eslint-config-js) and I had problems with it, this problem is not solved yet, why is it closed?

**Comment by waynzh** [comment]
You could try using [`files` patterns](https://eslint.org/docs/latest/use/configure/configuration-files-new), like:

```
[
  ...pluginVue.configs['flat/recommended'].map(config => ({
    ...config,
    files: ['**/*.vue'],
  })),
 // ...
]
```

or other format: 
```
[{
  files: ['**/*.vue'],
  // ...
  plugins: {
      vue: pluginVue
   },
   rules: {
      ...pluginVue.configs.base.rules,
      ...pluginVue.configs['vue3-essential'].rules,
      ...pluginVue.configs['vue3-strongly-recommended'].rules,
      ...pluginVue.configs['vue3-recommended'].rules,
   }
}]
```

**Comment by lvzhenbo** [comment]
@waynzh Ok thanks a lot, hopefully it will be added to the official documentation as eslint is no longer a separate tool for js only

**Comment by justdagege** [comment]
hi, @lvzhenbo  , i want to know how to fix this error? i have same problem

**Comment by lvzhenbo** [comment]
As stated above, restrict the rules to the necessary files rather than the global environment.

**Comment by etiennelenhart** [comment]
This really looks like a bug.
I think the `files: ['*.vue', '**/*.vue'],` in [base.js](https://github.com/vuejs/eslint-plugin-vue/blob/adc460da10dc3ca319de87a2c0ceba5a4d4d390c/lib/configs/flat/base.js#L20) only applies to the `vue/base/setup-for-vue` rules. The other rules extending those don't have any files restriction.
