### ISSUE TITLE
Cannot read property 'recommended' of undefined

### ISSUE THREAD

**Issue by SteveALee** [vuejs/eslint-plugin-vue#307]
**Tell us about your environment**

Windows 10

* **ESLint Version:** 4.14.0
* **eslint-plugin-vue Version:** 2.1.0
* **Node Version:** 8.9.1

* Windows 10
* visual studio code - no workspace settings for prettier or eslint 

**Please show your full configuration:**

Package.json
```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {},
  "scripts": {
    "lint": "eslint --ext .js,.vue ."
  },
  "devDependencies": {
    "eslint": "^4.14.0",
    "eslint-plugin-vue": "^2.1.0"
  }
}
```

.eslintrc.js
```
module.exports = {
  extends: ['plugin:vue/recommended']
  // required to lint *.vue files
}
```

**What did you do? Please include the actual source code causing the issue.**

```
npm i && npm run lint
```

**What did you expect to happen?**

lint to run

**What actually happened? Please include the actual, raw output from ESLint.**

```
Cannot read property 'recommended' of undefined
Referenced from: C:\projects\vuetest\.eslintrc.js
TypeError: Cannot read property 'recommended' of undefined
Referenced from: C:\projects\vuetest\.eslintrc.js
    at loadConfigFile (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:211:40)
    at loadFromDisk (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:486:18)
    at load (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:550:20)
    at configExtends.reduceRight (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:403:28)
    at loadFromDisk (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:514:22)
    at Object.load (C:\projects\vuetest\node_modules\eslint\lib\config\config-file.js:550:20)
    at Config.getLocalConfigHierarchy (C:\projects\vuetest\node_modules\eslint\lib\config.js:228:44)
    at Config.getConfigHierarchy (C:\projects\vuetest\node_modules\eslint\lib\config.js:180:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.1 lint: `eslint --ext .js,.vue .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steve\AppData\Roaming\npm-cache\_logs\2017-12-28T20_45_19_579Z-debug.log
```

This error which ever config I use (eg base
Other configs like eslint-plugin node work just fine

**Comment by SteveALee** [comment]
Oh FFS, my bad. I just noticed the readme is not for the latest stable version but for the 4.x beta!"

That was a big waste of time :(

Perhaps add a note? I know you say it's for version 4.x but not being at all familier with the versions I assumed that was the latest.

So how stable is the beta? can I rely on it?

thanks

**Comment by SteveALee** [comment]
I should just read the readme! Not just scan for the bits i want!
