### ISSUE TITLE
一个错误，，Cannot read property 'range' of null

### ISSUE THREAD

**Issue by ldwqh0** [vuejs/eslint-plugin-vue#386]
我的index.js代码中有如下导出语句
```javascript
export Module from './module'
```
在.eslintrc.js中使用如下配置
```javascript
extends: [  
  'plugin:vue/strongly-recommended',  
  'standard'
],
plugins: [
  'vue'
]
```
执行lint检查时，出现如下错误
```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenAfter (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\token-store\index.js:320:18)
    at ExportNamedDeclaration (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint-plugin-vue\lib\utils\indent-common.js:1025:43)
    at listeners.(anonymous function).forEach.listener (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (D:\Users\LiDong\Projects\hb\sources\ds\web\node_modules\eslint\lib\linter.js:1006:32)
```
不知道这是个错误还是bug.
I don't know this is my error or a but.

我的英语不是很好，但作者应该能明白，谢谢。

**Comment by michalsnik** [comment]
Hey @ldwqh0 , have you tried to add `babel-eslint` parser? It might be the case.
```
extends: [  
  'plugin:vue/strongly-recommended',  
  'standard'
],
parserOptions: [
  parser: 'babel-eslint'
]
```

**Comment by mysticatea** [comment]
The `export Module from "./module"` is not valid JavaScript code. As [the language spec](https://www.ecma-international.org/ecma-262/8.0/#sec-exports), `ExportClause` has to be enclosed by braces.

**Comment by michalsnik** [comment]
Yeah, you're right @mysticatea I confirmed it. Closing now :)

**Comment by ldwqh0** [comment]
https://github.com/tc39/proposal-export-default-from/blob/master/README.md

**Comment by ldwqh0** [comment]
@michalsnik 
看这个
https://github.com/tc39/proposal-export-default-from/blob/master/README.md
