### ISSUE TITLE
Cannot read proprty 'properties' of undefined

### ISSUE THREAD

**Issue by Vrashq** [vuejs/eslint-plugin-vue#390]
**Tell us about your environment**

* **ESLint Version:** 4.17.0
* **eslint-plugin-vue Version:** 4.2.2
* **Node Version:** 6.11.5

**Please show your full configuration:**

```
module.exports = {
    extends: [
        // add more generic rulesets here, such as:
        // 'eslint:recommended',
        'plugin:vue/recommended'
    ],
    rules: {
        // override/add rules settings here, such as:
        // 'vue/no-unused-vars': 'error'
    },
    parserOptions: {
        parser: "babel-eslint",
        ecmaVersion: 2017,
        sourceType: "module"
    }
};



```

When I ran the command "eslint --ext .js,.vue resources/assets/js", I've got the error below : 

```
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
    at Object.getComputedProperties (/home/jlenaou/Documents/teachme-vue/node_modules/eslint-plugin-vue/lib/utils/index.js:326:51)
    at Object.assign.utils.executeOnVue (/home/jlenaou/Documents/teachme-vue/node_modules/eslint-plugin-vue/lib/rules/no-async-in-computed-properties.js:133:42)
    at CallExpression:exit (/home/jlenaou/Documents/teachme-vue/node_modules/eslint-plugin-vue/lib/utils/index.js:472:9)
    at listeners.(anonymous function).forEach.listener (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/util/node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (/home/jlenaou/Documents/teachme-vue/node_modules/eslint/lib/linter.js:1009:32)
```

Thank you :)

**Comment by mysticatea** [comment]
Thank you for the report.

Would you provide repro steps?
Maybe can you make it on [our online demo](https://mysticatea.github.io/vue-eslint-demo/#eJyNlk2PnDgQhv9KxLmtkfY4akWKVlrtffeYi4ECnDE2Kds9TaL8931t82FgIu1hRs1TZdd3wc+qsS1Vr9Xd0zhp6enzV/Pp071Vj89/k9b2/hJ/fjX3l0Lh7hpWk094+VndKg6aXPX6E1ca5zk03rJwYSKuXv+4VcaKRjoSLTVasvQKWptAS+cE/lRvNmbHSTIJQ734QWx3btqLqnFWU/noP1Dx0vh0XEXjhcSz1YKpp+cKW6pD3++et6TJk3jInSAwIbl3B5ADGWmsiY+SN5pLoFWDXKaMrBT59bNoBiSn8cT5rqNwkh4Sc4Dbw/MUMj09S1FbZEaaaMkfJY5GtZJOau0HtqEfNhRMc7qx17aW+gSVMXD2o6oq85BatTmz00YZzwHK4n1Qntwkmy0Fo3pSKxJCO6DOXtbbdYbehZvH2uqV2Pob4tJ6U7GNl5uUKTtFO4Afy+0rc6S7U0BQYBdry3IvmR+UEzV1Fh156OlgWur2BwRKqF4rxqC90srQLmOSqG6tC+RkR6JTBkHMJ4q+l2WfBhMc7tWypj3gBaIvd4SQCE1IrpFTNoU8wSnhBst+QFoTZPoeFKKZFelMcFIoZ2Q2mWvn54lsju8R6AX9x6oO6NxhngYyu4dRipEdCTPW4t7GqwdtksGPGg1tnTK9qNHgb+RjQbcE/VYplgvPRyVKrbHM3kYVSmH8kX0P1tNJL9V8sbNJvrlnTJ3bcxnpKDFVa8xOoO7i4PIYsFWaAXkzGMzJ6pSQi9NGjiQmtjgfR1weLKNm0s0YNmXS0guxfRZlVfied1UXUnoeAq2I/6or5cdNs8Nl2+yRlPLUqeVYLDyOQTRFzJZLAZMjfsDJsyWH3QUcg7AmNYL08qCgWhLUdegO9z/CXV850dCRPz0sSbGmvxSeRyJiyy0qtxhMru2ydQ52r9VViBmXSFPy8yKMMA3K9RyjU2GZyQc2F2kuYhncJknD9xur8a6Psrdfk1/K54FIOwzn1rRugoeooSqcn3UJYyMfUV4Ja1XYWn+S5ZsuEMMm3y4Ue4zKBi75BXZFD64sTvMFfnDhiG+cq2KxuHbUXC1PfGVYpe8XGNsS8Netyon/R/3IJ/Pjv3Ncx1V+4d0qwmeI5QXGr7Avpv0rvv/+jF9ktyq9hRBzVceNj3WOxeOrX/8BbEpViw==)?

**Comment by Vrashq** [comment]
So, I tried to find in which file there was an error and I found it

**Comment by Vrashq** [comment]
I found the piece of code that makes it crash [here](https://mysticatea.github.io/vue-eslint-demo/#eJyNVstu2zoQ/RVBm8aA2QJ3mdsUKAp0XaB3mQ0ljSwmFKny4VgN8u/3UJRIPVKgBhJbZ4bzPDPUa1nrhsr78rOtjRjcl0fF7ajqovWqdkKrwpDV8krfdD9oRcrZuzr9PBWvj+rRGXLeqIK/cOGKH0b3wtJHLuVK82PPh7toOaOn4uFLtFDgI9o7Nw6k2yIpFA8PD8WHJZQPk7ti9dk4TqfuTlnrLf+clZPav8Hx2+mEb2h9/jQXoDyXxkuy5f0raqOsM7522jDrBzLl/T/nUmlWc0usoVpyw0NoNgkkt5bhT1xUwuCRG2KKLuw3GZ1x1RxUFapN60f3jorjyk3HRXC+kjijJTN0odsCNlT5yyVH3pAkR+zKM4LEGDcXuwFiIj31FZmt5JnGNSBFzWEwVGRBqR/cyOoOxakdmWhrKxy4g0RtwPRw26VMN2c4qzQqw1Xw5LYSS71YkBa8c53R/tIlCPzZWbxIXXG5A4VSCPa9rgp15VI0sbJDQg2ePZTZSycc2YHXqQS9uFHDJgh0QJ8dr5I5RS/Mjn2l5YLo6gl5SZlUdO14khqKQVEGEMdsfcEsyXaXEBSMDb01PLfMdcKyiloNRm447VVDbX5AooTuNaz30gkpFGWZIY7uVnIFWd4Sa4VCEuMOBe/5mqdeeQu7kleUE55B8DJDSIlAQrI1H6Ir1AlBMdtp4zqUdQIN/fIC2YyCZERwkgmreHQZexd3SwQ8fQL/jKg8mNuNQ0cqRxikGNkeK4I1sIvdc6Uk6VwvQWhthbqwCgR/Jhcamgr0R6XQLjxvlWiixjx7CRVohXJb7JfXjnZ6U89nP0nyZG+hdDbXMqA9x1QtOVuGvrNNyL3HVqk71E1hMActp4Icgla8JzYYjfNhxPnGM3o2rXjYmJaeD/SZlcUq9rirWj+V58pARfwX7Vq+3TQZnLdNzmQtn5i6HosZD2MQXJEx2qwFuNvIXBHk3pPF7gKc7grWcMc3CqIhRm0Ldti/SNdhwckQOBxt8ZuDJ86W8q+F+5EIsDYNOjc7jFdrki1zkKMWRyFmnKNMU5wHYQCnQTmeM2AqPMdL9CCNTVwnlyTT8P3Ba7D1XvWymXgp7wdi2mE4t5Q1Ca6sgiqzbpRrMBB5C8WVsHTFaO12smjpAGLY+PMBxR6jNYHX+AFsVxxcsDDNB/Adgz1e1o6Kq8WVofroeTBHDKv05QAGWgJ8O5ex8D/F73gyPv43hnVcxgvvXBJeQ7SZwfA6+VU138P99y28Wp7L6RZCzmUVNj7WORaPK9/+B/qFmgM=)

If you remove the brackets in the line 5, after "component", the error disapear.

**Comment by mysticatea** [comment]
I confirmed it. Thank you very much!!
