### ISSUE TITLE
Error while running ESLint: Cannot read property 'essential' of undefined.

### ISSUE THREAD

**Issue by SnooHD** [vuejs/eslint-plugin-vue#437]
**Tell us about your environment**
I am using a CLEAN Nuxt.js starter-template created with:
`vue init nuxt-community/starter-template <project-name>`
I was getting this error so i decided to update the packages to the latest version, yet this did not solve it.
I am using Atom with linter-eslint. `Lint HTML Files` is ticked, `text.html.vue` is added to the scope.

* **ESLint Version:**
4.19.0
* **eslint-plugin-vue Version:**
4.3.0
* **Node Version:**
8.10.0

**Please show your full configuration:**
```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {}
}
```

**What did you do? Please include the actual source code causing the issue.**
I created a fresh nuxt project with `vue init nuxt-community/starter-template test`

**What did you expect to happen?**
I expected eslint-plugin-vue to work.

**What actually happened? Please include the actual, raw output from ESLint.**
I am getting an error stating that `vue\` is undefined.

```
Cannot read property 'essential' of undefined
Referenced from: C:\Users\Mike\Nuxt\test.eslintrc.js
TypeError: Cannot read property 'essential' of undefined
Referenced from: C:\Users\Mike\Nuxt\test.eslintrc.js
    at loadConfigFile (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:217:40)
    at load (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:535:18)
    at configExtends.reduceRight (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:408:28)
    at Object.load (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:566:22)
    at loadConfig (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config.js:63:33)
    at getLocalConfig (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config.js:130:29)
    at Config.getConfig (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\config.js:260:26)
    at processText (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:224:33)
    at CLIEngine.executeOnText (C:\Users\Mike\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:754:26)
    at lintJob (file:///C:/Users/Mike/.atom/packages/linter-eslint/src/worker.js:17:28)
    at process. (file:///C:/Users/Mike/.atom/packages/linter-eslint/src/worker.js:67:24)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by michalsnik** [comment]
I just installed new project following those steps:

```
vue init nuxt-community/starter-template test
cd test
npm install
npm run lint
```

and everything worked fine with no errors. Can you do exactly that once again? Perhaps it's problem with your editor and not eslint or this plugin at all.

**Comment by SnooHD** [comment]
I can confirm that this works, i am getting this error in Atom only.
After checking around some more i noticed that `use global Eslint installation` was ticked in the `linter-eslint` settings.
When i unticked it, it all started to work; so that means my global installation is outdated.

simply ran `npm update -g --all-packages` and now we are good to go ^^

Thanks for your time! Problem is solved 😄
