### ISSUE TITLE
multiline-html-element-content-newline not supporting additional properties

### ISSUE THREAD

**Issue by patric-eberle** [vuejs/eslint-plugin-vue#792]
**Tell us about your environment**	
* **ESLint version: 5.12.1**	
* **eslint-plugin-vue version: 5.1.0**	
* **Node version: 10.15.1**	

**Please show your full configuration:**

```js
// https://eslint.org/docs/user-guide/configuring
const webpackConfig = require('./webpack.config');

module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module',
  },
  env: {
    browser: true,
  },
  extends: [
    'valantic',
    'plugin:vue/recommended',
  ],
  // required to lint *.vue files
  plugins: [
    'vue',
    // 'html' // eslint-plugin-html
  ],
  // Uses eslint-import-resolver-webpack
  settings: {
    'import/resolver': {
      webpack: {
        config: { // Linking the webpack.config.js instead caused console noise and linting issues
          resolve: webpackConfig().resolve
        }
      }
    }
  },
  // add your custom rules here
  rules: {
    'require-jsdoc': [2, {
      require: {
        FunctionDeclaration: true,
        MethodDefinition: true,
        ClassDeclaration: true,
        ArrowFunctionExpression: true,
        FunctionExpression: false
      }
    }],
    'id-length': [1, {
      min: 3,
      properties: 'always',
      exceptions: [
        '$',
        'a',
        'b',
        'e',
        'i',
        'in', // ember-cp-validations
        'j',
        'x',
        'y',
        '_', // _Lowdash
        'fs', // ember
        'gt', // ember-cp-validations
        'id',
        'DS', // ember-data
        'el', // Vue
        'on', // Vue
        'vm', // Vue
        'xs', // Bootstrap
        'sm', // Bootstrap
        'md', // Bootstrap
        'lg', // Bootstrap
        'xl', // Bootstrap
      ]
    }],

    // don't require .vue extension when importing
    'import/extensions': [0, 'always', {
      js: 'never',
      vue: 'never'
    }],
    'vue/max-attributes-per-line': [2, {
      'singleline': 3,
      'multiline': {
        'max': 1,
        'allowFirstLine': fal
      }
    }],
    'vue/name-property-casing': [2, 'kebab-case'],
    'vue/html-closing-bracket-newline': [0],
    'vue/multiline-html-element-content-newline': [2, {
      ignoreWhenEmpty: true,
      ignores: ['pre', 'textarea'],
      allowEmptyLines: false
    }],
    'indent': 0, // Indent is not working with html script tag. Use 'vue/script-indent' instead
    'vue/script-indent': ['error', 2, {
      'baseIndent': 1,
      'switchCase': 1
    }],
    'vue/html-self-closing': [2, {
      'html': {
        'void': 'never',
        'normal': 'never', // Don't close default elements
        'component': 'always'
      },
      'svg': 'always',
      'math': 'always'
    }]
  },
  globals: {
  }
};

```

**What did you do?**	
I linted the following template with the above configuration. 
```vue
<template>
  <div v-bem="modifiers"
       @mouseenter="hasHover = true"
       @mouseleave="hasHover = false">

    <!-- 'swiper' classes needed for the swiper plugin. -->
    <div ref="container"
         v-bem:container
         class="swiper-container">

      <!-- navigation -->
      <div v-bem:pagination
           class="swiper-pagination"></div>

      <!-- buttons-->
      <div v-bem:button-prev
           class="swiper-button-prev"></div>
      <div v-bem:button-next
           class="swiper-button-next"></div>

      <!-- modal -->
      <c-modal
        :open="modalOpen"
        :header-component="null"
        size="600"
        inner-spacing="0"
        mobile-transition="fade"
        @close="modalClose">
        <div v-bem:modal-close-icon @click="modalOpen = false">
          <e-icon icon="i-close"
                  width="25"
                  height="25"
                  inline />
        </div>
        <c-swiper-modal :images="pictures"
                        :initial-slide="swiper.activeIndex"
                        @change="onModalSlideChanged" />
      </c-modal>
    </div>

    <!-- counter -->
    <div v-if="pictures.length > 1" v-bem:counter>
      <div v-bem:counter-detail="{ image: true }">
        {{ $tc('c-swiper.images', images.length, {count: images.length}) }}
      </div>
      <div v-if="videos && videos.length" v-bem:counter-detail="{ video: true }">
        {{ $tc('c-swiper.videos', videos.length, {count: videos.length}) }}
      </div>
    </div>

  </div>
</template>
```

**What did you expect to happen?**
With the `vue/multiline-html-element-content-newline` enabled, I would expect it to throw an error about the empty lines inside a new element. This works fine as long as the rule is only configured with the error level.

**What actually happened?**
When I add a configuration for this rule as seen above and documented in the docs, ESLint throws an error:

```
Error: /Users/patriceberle/Documents/projects/vue-template/.eslintrc.js:
        Configuration for rule "vue/multiline-html-element-content-newline" is invalid:
        Value {"ignoreWhenEmpty":true,"ignores":["pre","textarea"],"allowEmptyLines":true} should NOT have additional properties.

    at validateRuleOptions (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config/config-validator.js:133:19)
    at Object.keys.forEach.id (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config/config-validator.js:176:9)
    at Array.forEach (<anonymous>)
    at validateRules (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config/config-validator.js:175:30)
    at Object.validate (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config/config-validator.js:262:5)
    at loadFromDisk (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config/config-file.js:521:19)
    at Object.load (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/config.js:342:29)
    at hashOfConfigFor (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/util/lint-result-cache.js:31:33)
    at LintResultCache.getCachedLintResults (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/util/lint-result-cache.js:86:30)
    at fileList.map.fileInfo (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/cli-engine.js:590:59)
    at Array.map (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/patriceberle/Documents/projects/vue-template/node_modules/eslint/lib/cli-engine.js:584:34)
error: uncaughtException: /Users/patriceberle/Documents/projects/vue-template/.eslintrc.js:
        Configuration for rule "vue/multiline-html-element-content-newline" is invalid:
        Value {"ignoreWhenEmpty":true,"ignores":["pre","textarea"],"allowEmptyLines":true} should NOT have additional properties.
```

**Comment by mysticatea** [comment]
Thank you for this report.

This is the correct behavior because your setting has an unknown option `allowEmptyLines`.
ESLint core checks invalid options with `ajv`. This is the error message of that.

**Comment by mob8607** [comment]
Hi, but the docs state that `allowEmptyLines` is a valid option:
https://eslint.vuejs.org/rules/multiline-html-element-content-newline.html#options

**Comment by armano2** [comment]
this option is not yet released, i think we should start indicating in version when option is added with badges to reduce confusion

**Comment by MarkSky** [comment]
I would like to know when will the `allowEmptyLines` option can be used?
