### ISSUE TITLE
Missing definitions for vue eslint rules

### ISSUE THREAD

**Issue by BrandonYeager** [vuejs/eslint-plugin-vue#903]
**Tell us about your environment**	
* **ESLint version: 5.16.0**	
* **eslint-plugin-vue version: 5.2.2**	
* **Node version: 12.2.0**	

**Please show your full configuration:**

```
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/recommended',
    'eslint:recommended'
  ],
  rules: {
    'no-console': 'error',
    'no-debugger': 'error',

    // Base Rules (Enabling Correct ESLint Parsing)
    // -------------------------
    'vue/comment-directive': 'error', // plugin:vue/recommended
    'vue/jsx-uses-vars': 'error', // plugin:vue/recommended

    // Priority A: Essential (Error Prevention)
    // -------------------------
    'vue/no-async-in-computed-properties': 'error', // plugin:vue/recommended
    'vue/no-dupe-keys': 'error', // plugin:vue/recommended
    'vue/no-duplicate-attributes': 'error', // plugin:vue/recommended
    'vue/no-parsing-error': 'error', // plugin:vue/recommended
    'vue/no-reserved-keys': 'error', // plugin:vue/recommended
    'vue/no-shared-component-data': 'error', // plugin:vue/recommended fixable
    'vue/no-side-effects-in-computed-properties': 'error', // plugin:vue/recommended
    'vue/no-template-key': 'error', // plugin:vue/recommended
    'vue/no-textarea-mustache': 'error', // plugin:vue/recommended
    'vue/no-unused-components': 'error', // plugin:vue/recommended
    'vue/no-unused-vars': 'error', // plugin:vue/recommended
    'vue/no-use-v-if-with-v-for': 'error', // plugin:vue/recommended
    'vue/require-component-is': 'error', // plugin:vue/recommended
    'vue/require-prop-type-constructor': 'error', // plugin:vue/recommended fixable
    'vue/require-render-return': 'error', // plugin:vue/recommended
    'vue/require-v-for-key': 'error', // plugin:vue/recommended
    'vue/require-valid-default-prop': 'error', // plugin:vue/recommended
    'vue/return-in-computed-property': 'error', // plugin:vue/recommended
    'vue/use-v-on-exact': 'error', // plugin:vue/recommended
    'vue/valid-template-root': 'error', // plugin:vue/recommended
    'vue/valid-v-bind': 'error', // plugin:vue/recommended
    'vue/valid-v-cloak': 'error', // plugin:vue/recommended
    'vue/valid-v-else-if': 'error', // plugin:vue/recommended
    'vue/valid-v-else': 'error', // plugin:vue/recommended
    'vue/valid-v-for': 'error', // plugin:vue/recommended
    'vue/valid-v-html': 'error', // plugin:vue/recommended
    'vue/valid-v-if': 'error', // plugin:vue/recommended
    'vue/valid-v-model': 'error', // plugin:vue/recommended
    'vue/valid-v-on': 'error', // plugin:vue/recommended
    'vue/valid-v-once': 'error', // plugin:vue/recommended
    'vue/valid-v-pre': 'error', // plugin:vue/recommended
    'vue/valid-v-show': 'error', // plugin:vue/recommended
    'vue/valid-v-text': 'error', // plugin:vue/recommended

    // Priority B: Strongly Recommended (Improving Readability)
    // -------------------------
    'vue/attribute-hyphenation': 'error', // plugin:vue/recommended fixable
    'vue/html-closing-bracket-newline': 'error', // plugin:vue/recommended fixable
    'vue/html-closing-bracket-spacing': 'error', // plugin:vue/recommended fixable
    'vue/html-end-tags': 'error', // plugin:vue/recommended fixable
    'vue/html-indent': 'error', // plugin:vue/recommended fixable
    'vue/html-quotes': 'error', // plugin:vue/recommended fixable
    'vue/html-self-closing': 'error', // plugin:vue/recommended fixable
    'vue/max-attributes-per-line': 'error', // plugin:vue/recommended fixable
    'vue/multiline-html-element-content-newline': 'error', // plugin:vue/recommended fixable
    'vue/mustache-interpolation-spacing': 'error', // plugin:vue/recommended fixable
    'vue/name-property-casing': 'error', // plugin:vue/recommended fixable
    'vue/no-multi-spaces': 'error', // plugin:vue/recommended fixable
    'vue/no-spaces-around-equal-signs-in-attribute': 'error', // plugin:vue/recommended fixable
    'vue/no-template-shadow': 'error', // plugin:vue/recommended
    'vue/prop-name-casing': 'error', // plugin:vue/recommended fixable
    'vue/require-default-prop': 'error', // plugin:vue/recommended
    'vue/require-prop-types': 'error', // plugin:vue/recommended
    'vue/singleline-html-element-content-newline': 'error', // plugin:vue/recommended fixable
    'vue/v-bind-style': 'error', // plugin:vue/recommended fixable
    'vue/v-on-style': 'error', // plugin:vue/recommended fixable

    // Priority C: Recommended (Minimizing Arbitrary Choices and Cognitive Overhead)
    // -------------------------
    'vue/attributes-order': 'error', // plugin:vue/recommended fixable
    'vue/no-v-html': 'error', // plugin:vue/recommended
    'vue/order-in-components': 'error', // plugin:vue/recommended fixable
    'vue/this-in-template': 'error', // plugin:vue/recommended

    // Uncategorized
    // -------------------------
    'vue/array-bracket-spacing': 'error', // fixable
    'vue/arrow-spacing': 'error', // fixable
    'vue/block-spacing': 'error', // fixable
    'vue/brace-style': 'error', // fixable
    'vue/camelcase': 'error',
    'vue/comma-dangle': 'error', // fixable
    'vue/component-name-in-template-casing': 'error', // fixable
    'vue/dot-location': 'error', // fixable
    'vue/eqeqeq': 'error', // fixable
    'vue/key-spacing': 'error', // fixable
    '**vue/keyword-spacing**': 'error', // fixable
    'vue/match-component-file-name': 'error',
    'vue/no-boolean-default': 'error', // fixable
    'vue/no-deprecated-scope-attribute': 'error', // fixable
    'vue/no-empty-pattern': 'error',
    'vue/no-restricted-syntax': 'error',
    'vue/object-curly-spacing': 'error', // fixable
    'vue/require-direct-export': 'error',
    'vue/script-indent': 'error', // fixable
    'vue/space-infix-ops': 'error', // fixable
    'vue/space-unary-ops': 'error', // fixable
    'vue/v-on-function-call': 'error', // fixable
    'vue/v-slot-style': 'error', // fixable
    'vue/valid-v-slot': 'error',
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}
```

**What did you do?**	

```vue
vue-cli-service lint
```

**What did you expect to happen?**
No errors

**What actually happened?**

$ vue-cli-service lint
```
$ vue-cli-service lint
error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at src\App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <img
  4 |       alt="Vue logo"


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at src\App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <img
  4 |       alt="Vue logo"


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at src\App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <img
  4 |       alt="Vue logo"


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at src\App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <img
  4 |       alt="Vue logo"


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at src\App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <img
  4 |       alt="Vue logo"


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at src\App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <img
  4 |       alt="Vue logo"


error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at src\components\HelloWorld.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="hello">
  3 |     <h1>{{ msg }}</h1>
  4 |     <p>


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at src\components\HelloWorld.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="hello">
  3 |     <h1>{{ msg }}</h1>
  4 |     <p>


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at src\components\HelloWorld.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="hello">
  3 |     <h1>{{ msg }}</h1>
  4 |     <p>


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at src\components\HelloWorld.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="hello">
  3 |     <h1>{{ msg }}</h1>
  4 |     <p>


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at src\components\HelloWorld.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="hello">
  3 |     <h1>{{ msg }}</h1>
  4 |     <p>


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at src\components\HelloWorld.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="hello">
  3 |     <h1>{{ msg }}</h1>
  4 |     <p>


error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at src\main.js:1:1:
> 1 | import Vue from 'vue'
    | ^
  2 | import App from './App.vue'
  3 | 
  4 | Vue.config.productionTip = false


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at src\main.js:1:1:
> 1 | import Vue from 'vue'
    | ^
  2 | import App from './App.vue'
  3 | 
  4 | Vue.config.productionTip = false


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at src\main.js:1:1:
> 1 | import Vue from 'vue'
    | ^
  2 | import App from './App.vue'
  3 | 
  4 | Vue.config.productionTip = false


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at src\main.js:1:1:
> 1 | import Vue from 'vue'
    | ^
  2 | import App from './App.vue'
  3 | 
  4 | Vue.config.productionTip = false


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at src\main.js:1:1:
> 1 | import Vue from 'vue'
    | ^
  2 | import App from './App.vue'
  3 | 
  4 | Vue.config.productionTip = false


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at src\main.js:1:1:
> 1 | import Vue from 'vue'
    | ^
  2 | import App from './App.vue'
  3 | 
  4 | Vue.config.productionTip = false


error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at .eslintrc.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   root: true,
  3 |   env: {
  4 |     node: true


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at .eslintrc.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   root: true,
  3 |   env: {
  4 |     node: true


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at .eslintrc.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   root: true,
  3 |   env: {
  4 |     node: true


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at .eslintrc.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   root: true,
  3 |   env: {
  4 |     node: true


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at .eslintrc.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   root: true,
  3 |   env: {
  4 |     node: true


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at .eslintrc.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   root: true,
  3 |   env: {
  4 |     node: true


error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at babel.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   presets: [
  3 |     '@vue/app'
  4 |   ]


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at babel.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   presets: [
  3 |     '@vue/app'
  4 |   ]


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at babel.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   presets: [
  3 |     '@vue/app'
  4 |   ]


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at babel.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   presets: [
  3 |     '@vue/app'
  4 |   ]


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at babel.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   presets: [
  3 |     '@vue/app'
  4 |   ]


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at babel.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   presets: [
  3 |     '@vue/app'
  4 |   ]


error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at postcss.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   plugins: {
  3 |     autoprefixer: {}
  4 |   }


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at postcss.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   plugins: {
  3 |     autoprefixer: {}
  4 |   }


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at postcss.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   plugins: {
  3 |     autoprefixer: {}
  4 |   }


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at postcss.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   plugins: {
  3 |     autoprefixer: {}
  4 |   }


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at postcss.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   plugins: {
  3 |     autoprefixer: {}
  4 |   }


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at postcss.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   plugins: {
  3 |     autoprefixer: {}
  4 |   }


error: Definition for rule 'vue/dot-location' was not found (vue/dot-location) at vue.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   lintOnSave: false
  3 | }
  4 | 


error: Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing) at vue.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   lintOnSave: false
  3 | }
  4 | 


error: Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute) at vue.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   lintOnSave: false
  3 | }
  4 | 


error: Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern) at vue.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   lintOnSave: false
  3 | }
  4 | 


error: Definition for rule 'vue/v-slot-style' was not found (vue/v-slot-style) at vue.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   lintOnSave: false
  3 | }
  4 | 


error: Definition for rule 'vue/valid-v-slot' was not found (vue/valid-v-slot) at vue.config.js:1:1:
> 1 | module.exports = {
    | ^
  2 |   lintOnSave: false
  3 | }
  4 | 


42 errors found.

 ERROR  Error: Process exited with code 1

Error: Process exited with code 1
    at exports.exit (C:\Users\BrandonYeager\Development\Other\test-missing-vue-eslint-rules\node_modules\@vue\cli-shared-utils\lib\exit.js:7:11)
    at lint (C:\Users\BrandonYeager\Development\Other\test-missing-vue-eslint-rules\node_modules\@vue\cli-plugin-eslint\lint.js:122:5)
    at C:\Users\BrandonYeager\Development\Other\test-missing-vue-eslint-rules\node_modules\@vue\cli-plugin-eslint\index.js:84:24
    at Service.run (C:\Users\BrandonYeager\Development\Other\test-missing-vue-eslint-rules\node_modules\@vue\cli-service\lib\Service.js:221:12)
    at Object.<anonymous> (C:\Users\BrandonYeager\Development\Other\test-missing-vue-eslint-rules\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)

Total task duration: 1.39s

```

**Comment by BrandonYeager** [comment]
Here's a summary of the rules that are causing the errors:
```
Definition for rule 'vue/dot-location' was not found (vue/dot-location)
Definition for rule 'vue/keyword-spacing' was not found (vue/keyword-spacing)
Definition for rule 'vue/no-deprecated-scope-attribute' was not found (vue/no-deprecated-scope-attribute)
Definition for rule 'vue/no-empty-pattern' was not found (vue/no-empty-pattern)
```

I tested every rule that was listed in the documentation at [https://eslint.vuejs.org/rules/].

**Comment by BrandonYeager** [comment]
This is a duplicate of #899 (I originally thought that my list of results was different)
